name: Kodular
title: Kodular
description: Drag and Drop Android App Creator. No coding required!

google_analytics: UA-102230060-3
google_ads: ca-pub-9439286719204795

social:
  twitter: https://twitter.com/KodularIO
  fb: https://www.facebook.com/Kodular
  github: https://github.com/Kodular
  gplus: https://plus.google.com/111643344046547332656
  telegram: https://telegram.me/Kodular
  instagram: https://instagram.com/Kodular

gems:
  - jekyll-redirect-from
