name: Makeroid
title: Makeroid | Home
description: Drag and drop Android app builder
google_analytics: UA-102230060-3
google_ads: ca-pub-9439286719204795
social:
  github: https://github.com/Makeroid
  twitter: https://twitter.com/MakeroidBuilder
  fb: https://www.facebook.com/Makeroid
  gplus:
